int64 imu_freq
int64 lid_freq
int64 odom_freq
int64[] cams_freq

int64 map_size
int64 oct_num
int64 new_idxs
int64 upd_idxs
int64 mean_bin
int64 start_bin
int64 scan_size
int64 buffer_size
float64 scan_time

float64 res_mean
float64 obs_min
int64 kf_iterations

float64 obs_score
float64 vert_score
float64 bin_score

int64 num_planes
int64 num_lines
int64 num_balls
int64 num_feats
int64 num_reject

float64 wt_mean
float64 wt_std
float64 wt_min
float64 wt_max

float64 rng_min
float64 rng_max
float64 rng_mean

float64 imu_time
float64 state_time
float64 map_time
float64 total_time

float64 imu_mean
float64 state_mean
float64 map_mean
float64 total_mean

float64 imu_max
float64 state_max
float64 map_max
float64 total_max

float64 lid_offset
float64 imu_offset

int64 run_time
int64 traj_dist
int64 ram_usage
int64 cpu_usage