/**:
    ros__parameters:

        mapping:
            map_resolution: 0.1
            pub_map_n_secs: 10 
            
        lidar:
            type: 2 # LIVOX = 1, VELODYNE = 2, OUSTER = 3, HESAI = 4
            rate: 10
            scan_lines: 16
            vertical_fov: 30.0
            min_range: 0.0
            max_range: 100.0
            topic:  "/velodyne_points"
            t_imu_lidar: [0.058, 0.008, 0.169]
            r_imu_lidar: [0.004, 0.001, -0.013, 1.000]

        imu:
            rate: 400
            acc_noise: 0.05
            gyr_noise: 0.02
            acc_bias: 0.002
            gyr_bias: 0.0004
            topic:  "/imu/data"